TARGET = demo_ecc

NUCLEI_SDK_ROOT = ../../..

# REQUIRE: ECC
# set to 1 or 2 for different ECC version
XLCFG_ECC := 1

# OPTIONAL: CCM, PMA, ICACHE, DCACHE, SMPCC
XLCFG_CCM := 1
XLCFG_PMA :=
XLCFG_ICACHE :=
XLCFG_DCACHE :=
XLCFG_SMPCC :=

SRCDIRS = .

INCDIRS = .

COMMON_FLAGS := -O2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
