TARGET = demo_stack_check

NUCLEI_SDK_ROOT = ../../..

# REQUIRE: STACK_CHECK
XLCFG_STACK_CHECK :=

SRCDIRS = . src

INCDIRS = . inc

COMMON_FLAGS := -O0

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
