TARGET = freertos_fprvv_demo
RTOS = FreeRTOS

NUCLEI_SDK_ROOT = ../../..

COMMON_FLAGS := -Os
CORE := nx900fd
ARCH_EXT := v_zvl128b
DOWNLOAD := ddr
STDCLIB := newlib_small

SRCDIRS = .
INCDIRS = .

LDLIBS := -lm


include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
