TARGET = smphello

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .

INCDIRS = .

COMMON_FLAGS := -O2

# Per-Core HEAP and STACK Size Settings
HEAPSZ ?= 2K
STACKSZ ?= 2K
# SMP CORE Number Settings
SMP ?= 2

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
