TARGET = demo_vnice

NUCLEI_SDK_ROOT ?= ../../..

SRCDIRS = .

INCDIRS = .

# REQUIRE: VNICE
XLCFG_VNICE :=

CORE ?= nx900fd

ARCH_EXT ?= v

COMMON_FLAGS :=

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
