# NOTE: This cpuconfig.mk is only valid when cpufeature.mk is not generated by nuclei_gen
# NOTE: extra XLCFG_xxx make variables to control
# cpu feature present or not which is only internally used by Nuclei(XinLai)
# This will affect the cpufeature.h and evalsoc.h
XLCFG_SPMP ?=
ifeq ($(XLCFG_SPMP),1)
XLCFG_TEE := 1
COMMON_FLAGS += -DCFG_HAS_SPMP
endif

XLCFG_SMPU ?=
ifeq ($(XLCFG_SMPU),1)
XLCFG_TEE := 1
COMMON_FLAGS += -DCFG_HAS_SMPU
endif

XLCFG_TEE ?=
ifeq ($(XLCFG_TEE),1)
COMMON_FLAGS += -DCFG_HAS_TEE
endif

XLCFG_PMP ?=
ifeq ($(XLCFG_PMP),1)
COMMON_FLAGS += -DCFG_HAS_PMP
else ifeq ($(XLCFG_PMP),0)
COMMON_FLAGS += -DUNDEF_CFG_HAS_PMP
endif

XLCFG_CCM ?=
ifeq ($(XLCFG_CCM),1)
COMMON_FLAGS += -DCFG_HAS_IOCC
endif

XLCFG_ECLIC ?=
ifeq ($(XLCFG_ECLIC),1)
COMMON_FLAGS += -DCFG_HAS_CLIC
else ifeq ($(XLCFG_ECLIC),2)
COMMON_FLAGS += -DCFG_HAS_ECLICV2 -DCFG_HAS_CLIC
else ifeq ($(XLCFG_ECLIC),0)
COMMON_FLAGS += -DUNDEF_CFG_HAS_CLIC
endif

XLCFG_PLIC ?=
ifeq ($(XLCFG_PLIC),1)
COMMON_FLAGS += -DCFG_HAS_PLIC
endif

XLCFG_SYSTIMER ?=
ifeq ($(XLCFG_SYSTIMER),1)
COMMON_FLAGS += -DCFG_TMR_PRIVATE
else ifeq ($(XLCFG_SYSTIMER),0)
COMMON_FLAGS += -DUNDEF_CFG_TMR_PRIVATE
endif

XLCFG_SSTC ?=
ifeq ($(XLCFG_SSTC),1)
COMMON_FLAGS += -DCFG_HAS_ISA_SSTC
endif

XLCFG_SMODE ?=
ifeq ($(XLCFG_SMODE),1)
COMMON_FLAGS += -DCFG_HAS_SMODE
endif

XLCFG_CIDU ?=
ifeq ($(XLCFG_CIDU),1)
COMMON_FLAGS += -DCFG_HAS_IDU
endif

XLCFG_HPM ?=
ifeq ($(XLCFG_HPM),1)
COMMON_FLAGS += -DCFG_HAS_HPM
endif

XLCFG_SMPCC ?=
ifeq ($(XLCFG_SMPCC),1)
COMMON_FLAGS += -DCFG_HAS_SMP
else ifeq ($(XLCFG_SMPCC),0)
COMMON_FLAGS += -DUNDEF_CFG_HAS_SMP
endif

XLCFG_ECC ?=
ifeq ($(XLCFG_ECC),1)
COMMON_FLAGS += -DCFG_HAS_ECC
else ifeq ($(XLCFG_ECC),2)
COMMON_FLAGS += -DCFG_HAS_ECC -DCFG_ECC_CODE_XOR
else ifeq ($(XLCFG_ECC),0)
COMMON_FLAGS += -DUNDEF_CFG_HAS_ECC
endif
