TARGET = demo_smode_plic

NUCLEI_SDK_ROOT = ../../..

# Require S-Mode and PLIC and PMP extension
# set to 1 if present
XLCFG_PLIC :=

SRCDIRS = .

INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
