TARGET = threadx_module_manager
RTOS = ThreadX
THREADX_MODULE := 1

# define TX_INCLUDE_USER_DEFINE_FILE to include user defines in tx_user.h
COMMON_FLAGS := -O2 -DTX_INCLUDE_USER_DEFINE_FILE

NUCLEI_SDK_ROOT = ../../../..

SRCDIRS = .
INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
