TARGET = freertos_demo
RTOS = FreeRTOS

# REQUIRE: ECLIC, SYSTIMER
XLCFG_SYSTIMER :=
XLCFG_ECLIC :=

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .
INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
