TARGET = lowpower

NUCLEI_SDK_ROOT = ../../..

SRCDIRS = .

INCDIRS = .

# REQUIRE: ECLIC, SYSTIMER
XLCFG_SYSTIMER :=
XLCFG_ECLIC :=

COMMON_FLAGS := -O2

STDCLIB ?= newlib_small

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
