TARGET = demo_smode_eclic

NUCLEI_SDK_ROOT = ../../..

# Require S-Mode and PMP extension
# set to 1 if present
XLCFG_SMODE :=

SRCDIRS = .

INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
