TARGET = demo_smode_eclic

NUCLEI_SDK_ROOT = ../../..

# REQUIRE: SMODE, ECLIC, PMP, SYSTIMER
# set to 1 if present
XLCFG_SMODE :=
XLCFG_ECLIC :=
XLCFG_PMP :=
XLCFG_SYSTIMER :=

SRCDIRS = .

INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
