TARGET = freertos_smpdemo
RTOS = FreeRTOS

NUCLEI_SDK_ROOT = ../../..

SMP ?= 2

CORE ?= nx900

DOWNLOAD ?= sram

STACKSZ ?= 2K

SRCDIRS = .
INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
