TARGET = demo_smode_clint

NUCLEI_SDK_ROOT = ../../..

# REQUIRE: SSTC, PMP, SYSTIMER
# set to 1 if present
XLCFG_SSTC := 1
XLCFG_PMP :=
XLCFG_SYSTIMER :=

SRCDIRS = .

INCDIRS = .

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
